# Generated by Django 6.0 on 2025-12-19 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('fsm_state', models.CharField(default='greeting', max_length=64)),
                ('slots', models.JSONField(default=dict)),
                ('external_user_id_encrypted', models.TextField(blank=True, default='')),
                ('idempotency_salt', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='conversatio_status_6b4c28_idx'), models.Index(fields=['expires_at'], name='conversatio_expires_a2995f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traits', models.JSONField(default=dict)),
                ('grades', models.JSONField(default=dict)),
                ('preferences', models.JSONField(default=dict)),
                ('version', models.CharField(default='v1', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='conversations.session')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('system', 'system')], max_length=16)),
                ('content_encrypted', models.TextField()),
                ('idempotency_key', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('nlp', models.JSONField(default=dict)),
                ('fsm_state', models.CharField(blank=True, default='', max_length=64)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'created_at'], name='conversatio_session_d11ba7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('session', 'idempotency_key'), name='uniq_message_idem_per_session')],
            },
        ),
    ]
