# Generated by Django 6.0 on 2025-12-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="owner_uid",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
    ]
