# Generated by Django 6.0 on 2026-02-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_fix_session_last_activity_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='conversatio_session_e9a402_idx',
            old_name='conv_msg_idem_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='conversatio_owner_u_556c47_idx',
            old_name='conv_sess_owner_activity_idx',
        ),
    ]
