# Generated by Django 6.0 on 2025-12-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('college_student', 'College/University Student'), ('college_graduate', 'College/University Graduate')], max_length=32)),
                ('universal', models.JSONField(blank=True, default=dict)),
                ('high_school', models.JSONField(blank=True, default=dict)),
                ('college', models.JSONField(blank=True, default=dict)),
                ('riasec_answers', models.JSONField(blank=True, default=dict)),
                ('riasec_scores', models.JSONField(blank=True, default=dict)),
                ('riasec_top', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=dict)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('work_style', models.JSONField(blank=True, default=dict)),
                ('lifestyle', models.JSONField(blank=True, default=dict)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(blank=True, default='incomplete', max_length=32)),
                ('version', models.CharField(blank=True, default='v1', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='accounts.userprofile')),
            ],
        ),
    ]
