"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from urllib.parse import urlparse
from django.core.exceptions import ImproperlyConfigured
from cryptography.fernet import Fernet

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')
_django_env = (os.getenv('DJANGO_ENV') or os.getenv('ENVIRONMENT') or '').strip().lower()
if _django_env in ('prod', 'production') and DEBUG:
    raise ImproperlyConfigured('DJANGO_DEBUG must be false when DJANGO_ENV is production')

_secret_key_env = (os.getenv('DJANGO_SECRET_KEY') or '').strip()
if _secret_key_env:
    SECRET_KEY = _secret_key_env
else:
    if DEBUG:
        SECRET_KEY = 'django-insecure-hsk@9zfoe#0s*swj-3g#076^$%x54a#&!zkc*&35$vh38i7md_'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false')

_allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1'] if DEBUG else []
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS must be set when DJANGO_DEBUG is false')


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'catalog',
    'accounts',
    'conversations',
    'onetdata',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'utils.drf_exceptions.drf_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('DRF_THROTTLE_ANON', '60/min'),
        'user': os.getenv('DRF_THROTTLE_USER', '600/min'),
        # ↓ Applied specifically to LLM-backed chat endpoints to protect API quota.
        'chat_message': os.getenv('DRF_THROTTLE_CHAT_MESSAGE', '20/min'),
    },
}

_rag_use_pgvector = os.getenv('RAG_USE_PGVECTOR', '0').strip().lower() in ('1', 'true', 'yes')
_db_url_for_apps = os.getenv('DATABASE_URL', '').strip()
if _rag_use_pgvector and _db_url_for_apps:
    # pgvector requires Postgres; DATABASE_URL indicates we use Postgres in this project.
    INSTALLED_APPS.insert(0, 'django.contrib.postgres')
    INSTALLED_APPS.insert(0, 'vectorstore')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

# CORS configuration
_cors_allowed = os.getenv('CORS_ALLOWED_ORIGINS', '')
if _cors_allowed:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_allowed.split(',') if o.strip()]
else:
    CORS_ALLOW_ALL_ORIGINS = DEBUG

_csrf_trusted = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _csrf_trusted:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted.split(',') if o.strip()]
elif not DEBUG and _cors_allowed:
    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

RUNNING_TESTS = 'test' in sys.argv

_db_url = os.getenv('DATABASE_URL', '').strip()
if RUNNING_TESTS:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'test_db.sqlite3',
        }
    }
elif _db_url:
    _p = urlparse(_db_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _p.path.lstrip('/'),
            'USER': _p.username or '',
            'PASSWORD': _p.password or '',
            'HOST': _p.hostname or '',
            'PORT': str(_p.port or ''),
        }
    }
else:
    raise ImproperlyConfigured(
        'DATABASE_URL must be set (Postgres is required). '
        'Example: postgres://postgres:password@127.0.0.1:5432/delphine'
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- Conversations Engine Settings ---
# TTL for conversation sessions (in minutes)
CONV_SESSION_TTL_MINUTES = int(os.getenv('CONV_SESSION_TTL_MINUTES', '60') or '60')

CHAT_PLANNER_ENABLED = os.getenv('CHAT_PLANNER_ENABLED', '0').strip().lower() in ('1', 'true', 'yes')
CHAT_PLANNER_SHADOW_MODE = os.getenv('CHAT_PLANNER_SHADOW_MODE', '0').strip().lower() in ('1', 'true', 'yes')

# Encryption key for PII at rest (Fernet URL-safe base64). If empty, plaintext will be stored.
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
PII_ENCRYPTION_KEY = os.getenv('PII_ENCRYPTION_KEY', '').strip()

if not DEBUG and not RUNNING_TESTS:
    if not PII_ENCRYPTION_KEY:
        raise ImproperlyConfigured('PII_ENCRYPTION_KEY must be set in production')
    try:
        Fernet(PII_ENCRYPTION_KEY.encode('utf-8'))
    except Exception as e:
        raise ImproperlyConfigured('PII_ENCRYPTION_KEY is invalid') from e

# --- NLP Settings ---
# Confidence threshold for free-text parsing; below this we ask clarifying questions.
NLP_MIN_CONFIDENCE = float(os.getenv('NLP_MIN_CONFIDENCE', '0.4') or '0.4')
# NLP provider selection: 'local' (default lightweight) or 'gemini' (requires GEMINI_API_KEY)
NLP_PROVIDER = (os.getenv('NLP_PROVIDER', 'local') or 'local').strip().lower()
# Gemini API key (optional). If empty, local NLP is used.
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '').strip()
# Gemini Model name (when using Gemini). Defaults to a fast model.
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-1.5-flash').strip()

# --- RAG / Vector Search Settings ---
RAG_USE_PGVECTOR = _rag_use_pgvector and bool(_db_url_for_apps)
RAG_EMBED_DIM = int(os.getenv('RAG_EMBED_DIM', '768') or '768')
GEMINI_EMBEDDING_MODEL = (os.getenv('GEMINI_EMBEDDING_MODEL', 'gemini-embedding-001') or 'gemini-embedding-001').strip()

# --- Default primary key type ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Celery ---
# Set CELERY_BROKER_URL in env to a Redis URL (e.g., redis://localhost:6379/0)
# or leave unset to use an in-process "always eager" fallback for development.
_celery_broker = os.getenv('CELERY_BROKER_URL', '').strip()
_celery_backend = os.getenv('CELERY_RESULT_BACKEND', '').strip()

if _celery_broker:
    CELERY_BROKER_URL = _celery_broker
    CELERY_RESULT_BACKEND = _celery_backend or _celery_broker
    CELERY_TASK_ALWAYS_EAGER = False
else:
    # Development fallback: run tasks synchronously in the same process
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# Expire task results after 1 hour to avoid unbounded result storage
CELERY_RESULT_EXPIRES = 3600
CELERY_TASK_TRACK_STARTED = True
# Allow LLM tasks up to 90 s before being killed
CELERY_TASK_SOFT_TIME_LIMIT = 75
CELERY_TASK_TIME_LIMIT = 90

# --- Logging ---
_log_level = 'DEBUG' if DEBUG else 'INFO'
_log_handlers = ['console']
if DEBUG:
    _log_handlers.append('file')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {process:d} {message}',
            'style': '{',
        },
        'json': {
            '()': 'logging.Formatter',
            'format': '{"time":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","pid":%(process)d,"msg":%(message)s}',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if DEBUG else 'json',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'debug.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': _log_handlers,
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': _log_handlers,
            'level': 'ERROR',
            'propagate': True,
        },
        'django.security': {
            'handlers': _log_handlers,
            'level': 'ERROR',
            'propagate': True,
        },
        # App loggers
        'accounts': {
            'handlers': _log_handlers,
            'level': _log_level,
            'propagate': True,
        },
        'conversations': {
            'handlers': _log_handlers,
            'level': _log_level,
            'propagate': True,
        },
        'catalog': {
            'handlers': _log_handlers,
            'level': _log_level,
            'propagate': True,
        },
        'vectorstore': {
            'handlers': _log_handlers,
            'level': _log_level,
            'propagate': True,
        },
        'utils': {
            'handlers': _log_handlers,
            'level': _log_level,
            'propagate': True,
        },
    },
}
