"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-hsk@9zfoe#0s*swj-3g#076^$%x54a#&!zkc*&35$vh38i7md_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

_allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()] if _allowed_hosts_env else (['*'] if DEBUG else [])


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'catalog',
    'accounts',
    'conversations',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

_rag_use_pgvector = os.getenv('RAG_USE_PGVECTOR', '0').strip().lower() in ('1', 'true', 'yes')
_db_url_for_apps = os.getenv('DATABASE_URL', '').strip()
if _rag_use_pgvector and _db_url_for_apps:
    # pgvector requires Postgres; DATABASE_URL indicates we use Postgres in this project.
    INSTALLED_APPS.insert(0, 'django.contrib.postgres')
    INSTALLED_APPS.insert(0, 'vectorstore')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

# CORS configuration
_cors_allowed = os.getenv('CORS_ALLOWED_ORIGINS', '')
if _cors_allowed:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_allowed.split(',') if o.strip()]
else:
    CORS_ALLOW_ALL_ORIGINS = DEBUG

_csrf_trusted = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _csrf_trusted:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted.split(',') if o.strip()]
elif not DEBUG and _cors_allowed:
    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

RUNNING_TESTS = 'test' in sys.argv

_db_url = os.getenv('DATABASE_URL', '').strip()
if RUNNING_TESTS:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'test_db.sqlite3',
        }
    }
elif _db_url:
    _p = urlparse(_db_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _p.path.lstrip('/'),
            'USER': _p.username or '',
            'PASSWORD': _p.password or '',
            'HOST': _p.hostname or '',
            'PORT': str(_p.port or ''),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- Conversations Engine Settings ---
# TTL for conversation sessions (in minutes)
CONV_SESSION_TTL_MINUTES = int(os.getenv('CONV_SESSION_TTL_MINUTES', '60') or '60')

# Encryption key for PII at rest (Fernet URL-safe base64). If empty, plaintext will be stored.
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
PII_ENCRYPTION_KEY = os.getenv('PII_ENCRYPTION_KEY', '').strip()

# --- NLP Settings ---
# Confidence threshold for free-text parsing; below this we ask clarifying questions.
NLP_MIN_CONFIDENCE = float(os.getenv('NLP_MIN_CONFIDENCE', '0.4') or '0.4')
# NLP provider selection: 'local' (default lightweight) or 'gemini' (requires GEMINI_API_KEY)
NLP_PROVIDER = (os.getenv('NLP_PROVIDER', 'local') or 'local').strip().lower()
# Gemini API key (optional). If empty, local NLP is used.
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '').strip()
# Gemini Model name (when using Gemini). Defaults to a fast model.
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-1.5-flash').strip()

# --- RAG / Vector Search Settings ---
RAG_USE_PGVECTOR = _rag_use_pgvector and bool(_db_url_for_apps)
RAG_EMBED_DIM = int(os.getenv('RAG_EMBED_DIM', '768') or '768')
GEMINI_EMBEDDING_MODEL = (os.getenv('GEMINI_EMBEDDING_MODEL', 'gemini-embedding-001') or 'gemini-embedding-001').strip()
