# Generated by Django 6.0 on 2026-03-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetdata', '0003_onet_occupation_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnetContentElement',
            fields=[
                ('element_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('element_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1500)),
            ],
            options={
                'db_table': 'content_model_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnetEducationTrainingExperience',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('data_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('n', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('standard_error', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('lower_ci_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('upper_ci_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('recommend_suppress', models.CharField(blank=True, max_length=1, null=True)),
                ('date_updated', models.DateField()),
                ('domain_source', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'education_training_experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnetEteCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.DecimalField(decimal_places=0, max_digits=3)),
                ('category_description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'ete_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnetInterest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_updated', models.DateField()),
                ('domain_source', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'interests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnetJobZone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_updated', models.DateField()),
                ('domain_source', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'job_zones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnetJobZoneReference',
            fields=[
                ('job_zone', models.DecimalField(decimal_places=0, max_digits=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('experience', models.CharField(max_length=500)),
                ('education', models.CharField(max_length=500)),
                ('job_training', models.CharField(max_length=500)),
                ('examples', models.CharField(max_length=500)),
                ('svp_range', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'job_zone_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnetOccupation',
            fields=[
                ('onetsoc_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'occupation_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnetRelatedOccupation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relatedness_tier', models.CharField(max_length=50)),
                ('related_index', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'related_occupations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnetScale',
            fields=[
                ('scale_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('scale_name', models.CharField(max_length=50)),
                ('minimum', models.DecimalField(decimal_places=0, max_digits=4)),
                ('maximum', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
            options={
                'db_table': 'scales_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnetSkill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('n', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('standard_error', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('lower_ci_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('upper_ci_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('recommend_suppress', models.CharField(blank=True, max_length=1, null=True)),
                ('not_relevant', models.CharField(blank=True, max_length=1, null=True)),
                ('date_updated', models.DateField()),
                ('domain_source', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnetTaskStatement',
            fields=[
                ('task_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=1000)),
                ('task_type', models.CharField(blank=True, max_length=12, null=True)),
                ('incumbents_responding', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('date_updated', models.DateField()),
                ('domain_source', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'task_statements',
                'managed': False,
            },
        ),
    ]
