# Generated by Django 6.0 on 2025-12-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.field')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('county', models.CharField(blank=True, max_length=64)),
                ('website', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['region'], name='catalog_ins_region_89ea62_idx'), models.Index(fields=['county'], name='catalog_ins_county_9719ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='NormalizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PROGRAM_NAME', 'Program Name'), ('INSTITUTION_NAME', 'Institution Name'), ('LEVEL', 'Level'), ('SUBJECT', 'Subject'), ('REGION', 'Region')], max_length=32)),
                ('source_value', models.CharField(db_index=True, max_length=255)),
                ('normalized_value', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['type', 'source_value'],
                'unique_together': {('type', 'source_value')},
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('level', models.CharField(choices=[('bachelor', 'Bachelor'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=32)),
                ('campus', models.CharField(blank=True, max_length=128)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('duration_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('award', models.CharField(blank=True, max_length=128)),
                ('mode', models.CharField(blank=True, max_length=64)),
                ('subject_requirements', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='catalog.field')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='catalog.institution')),
            ],
            options={
                'ordering': ['normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='DedupMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('duplicate_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedup_duplicate', to='catalog.program', unique=True)),
                ('master_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedup_master', to='catalog.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('group', models.CharField(blank=True, max_length=64)),
                ('alt_codes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['group'], name='catalog_sub_group_c196db_idx')],
            },
        ),
        migrations.CreateModel(
            name='YearlyCutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('cutoff', models.DecimalField(decimal_places=3, max_digits=6)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='catalog.program')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['level'], name='catalog_pro_level_d6047b_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['region'], name='catalog_pro_region_eeef0d_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['institution', 'level'], name='catalog_pro_institu_dee4d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('institution', 'normalized_name', 'level', 'campus')},
        ),
        migrations.AddIndex(
            model_name='yearlycutoff',
            index=models.Index(fields=['year'], name='catalog_yea_year_00df91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='yearlycutoff',
            unique_together={('program', 'year')},
        ),
    ]
