# Generated by Django 6.0 on 2025-12-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterSubjectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_pattern', models.CharField(db_index=True, max_length=255)),
                ('subjects_grammar', models.TextField()),
            ],
            options={
                'ordering': ['program_pattern'],
            },
        ),
        migrations.CreateModel(
            name='ProgramOfferingBroadAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_normalized_name', models.CharField(max_length=255, unique=True)),
                ('offerings_count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['program_normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='CodeCorrectionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_code_before', models.CharField(blank=True, max_length=64)),
                ('program_code_after', models.CharField(blank=True, max_length=64)),
                ('correction_type', models.CharField(blank=True, max_length=64)),
                ('institution_code', models.CharField(blank=True, max_length=32)),
                ('group_key', models.CharField(blank=True, max_length=128)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['correction_type'], name='catalog_cod_correct_6dbb02_idx')],
            },
        ),
        migrations.CreateModel(
            name='ETLRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=64)),
                ('config_path', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='catalog_etl_action_7aa6c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramOfferingAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_normalized_name', models.CharField(db_index=True, max_length=255)),
                ('course_suffix', models.CharField(blank=True, max_length=16)),
                ('offerings_count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['program_normalized_name', 'course_suffix'],
                'unique_together': {('program_normalized_name', 'course_suffix')},
            },
        ),
        migrations.CreateModel(
            name='ProgramRequirementNormalized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required', models.JSONField(blank=True, default=list)),
                ('groups', models.JSONField(blank=True, default=list)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_requirements', to='catalog.program')),
            ],
            options={
                'ordering': ['program'],
            },
        ),
        migrations.CreateModel(
            name='DedupCandidateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_code', models.CharField(blank=True, max_length=32)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('bachelor', 'Bachelor'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=32)),
                ('campus', models.CharField(blank=True, max_length=128)),
                ('rows_count', models.PositiveIntegerField(default=0)),
                ('program_codes', models.JSONField(blank=True, default=list)),
                ('name_variants', models.JSONField(blank=True, default=list)),
                ('suggested_master_program_code', models.CharField(blank=True, max_length=64)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedup_candidate_groups', to='catalog.institution')),
            ],
            options={
                'ordering': ['-rows_count'],
                'indexes': [models.Index(fields=['level'], name='catalog_ded_level_bf7486_idx'), models.Index(fields=['campus'], name='catalog_ded_campus_4a54ef_idx')],
                'unique_together': {('institution', 'normalized_name', 'level', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='DedupSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_code', models.CharField(blank=True, max_length=32)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('duplicate_groups', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedup_summaries', to='catalog.institution')),
            ],
            options={
                'ordering': ['-duplicate_rows'],
                'unique_together': {('institution',)},
            },
        ),
        migrations.CreateModel(
            name='DQReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=64)),
                ('scope', models.CharField(blank=True, max_length=64)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dq_entries', to='catalog.etlrun')),
            ],
            options={
                'ordering': ['metric_name'],
                'indexes': [models.Index(fields=['metric_name'], name='catalog_dqr_metric__5692cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.CharField(max_length=128)),
                ('town', models.CharField(blank=True, max_length=128)),
                ('county', models.CharField(blank=True, max_length=64)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='catalog.institution')),
            ],
            options={
                'ordering': ['institution', 'campus'],
                'indexes': [models.Index(fields=['region'], name='catalog_ins_region_aa9328_idx'), models.Index(fields=['county'], name='catalog_ins_county_a3f895_idx')],
                'unique_together': {('institution', 'campus')},
            },
        ),
    ]
