# Generated by Django 6.0 on 2025-12-18 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_clustersubjectrule_programofferingbroadaggregate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRequirementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('pick', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_groups', to='catalog.program')),
            ],
            options={
                'ordering': ['program', 'order'],
                'unique_together': {('program', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProgramRequirementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_code', models.CharField(blank=True, max_length=32)),
                ('min_grade', models.CharField(blank=True, max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.programrequirementgroup')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_options', to='catalog.subject')),
            ],
            options={
                'ordering': ['group', 'order'],
                'indexes': [models.Index(fields=['subject_code'], name='catalog_pro_subject_63084e_idx')],
            },
        ),
    ]
