# Generated by Django 6.0 on 2025-12-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_programrequirementgroup_programrequirementoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSuffixMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_suffix', models.CharField(max_length=16, unique=True)),
                ('normalized_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['course_suffix'],
            },
        ),
    ]
