# Generated by Django 6.0 on 2025-12-19 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_coursesuffixmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('program_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='KES', max_length=16)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('raw_cost', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='catalog.program')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['program_code', 'source_id'], name='catalog_pro_program_68a203_idx')],
                'unique_together': {('program_code', 'source_id')},
            },
        ),
    ]
